pipeline:
  name: branch-rename-again
  identifier: branch
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags:
    app: test
    pipeline: branch
  stages:
    - stage:
        name: branch
        identifier: branch
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_6
                  identifier: ShellScript_6
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          rm -rf *

                          touch zipp.txt

                          tar -cvzf zipr.tgz zipp.txt

                          ls

                          tar -xvzf zipr.tgz
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: echo "<+infra.connector.name>-test"
                    environmentVariables: []
                    outputVariables: []
                    executionTarget: {}
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - _project_all_users
                        - <+ <+stage.variables.module> == "testuser"?"account.test2":"_project_all_users">
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo test
                          echo <+stage.delegateSelectors>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - stepGroup:
                  name: test
                  identifier: test
                  steps:
                    - parallel:
                        - step:
                            type: ShellScript
                            name: ShellScript_3
                            identifier: ShellScript_3
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo hi
                                    echo <+matrix.listOfString>
                                    echo <+stage.delegateSelectors>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                        - step:
                            type: ShellScript
                            name: ShellScript_4
                            identifier: ShellScript_4
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo hi2
                                    echo <+stage.delegateSelectors>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                    - step:
                        type: ShellScript
                        name: ShellScript_5
                        identifier: ShellScript_5
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo hi3
                                echo <+stage.delegateSelectors>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
          environment:
            environmentRef: delegate
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s
        tags: {}
        variables:
          - name: module
            type: String
            description: ""
            required: false
            value: <+input>
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: ServerlessAwsLambda
          service:
            serviceRef: serverless
          execution:
            steps:
              - stepGroup:
                  steps:
                    - step:
                        type: DownloadManifests
                        name: DownloadManifests
                        identifier: DownloadManifests
                        spec: {}
                        failureStrategies: []
                    - step:
                        identifier: Serverless_Aws_Lambda_Prepare_Rollback
                        type: ServerlessAwsLambdaPrepareRollbackV2
                        name: Serverless Aws Lambda Prepare Rollback
                        timeout: 10m
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/serverless-preparerollback:3.30.1-2.0.0
                          imagePullPolicy: Always
                          resources:
                            limits:
                              memory: 2G
                    - step:
                        identifier: Serverless_Aws_Lambda_Package
                        type: ServerlessAwsLambdaPackageV2
                        name: Serverless Aws Lambda Package
                        timeout: 10m
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/serverless-package:3.30.1-1.1.0
                          resources:
                            limits:
                              memory: 1G
                          imagePullPolicy: Always
                        when:
                          stageStatus: Success
                        failureStrategies: []
                    - step:
                        identifier: Serverless_Aws_Lambda_Deploy
                        type: ServerlessAwsLambdaDeployV2
                        name: Serverless Aws Lambda Deploy
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/serverless-deploy:3.30.1-1.0.2
                          imagePullPolicy: Always
                          resources:
                            limits:
                              memory: 1G
                        timeout: 10m
                        when:
                          stageStatus: Success
                        failureStrategies: []
                  name: Serverless Step Group
                  identifier: serverless_step_group
                  sharedPaths: []
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: default
            rollbackSteps:
              - stepGroup:
                  identifier: serverless_rollback_step_group
                  name: Serverless Rollback Step Group
                  steps:
                    - step:
                        identifier: Serverless_Aws_Lambda_Rollback
                        type: ServerlessAwsLambdaRollbackV2
                        name: Serverless Aws Lambda Rollback
                        timeout: 10m
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/serverless-rollback:3.30.1-1.0.2
                          imagePullPolicy: Always
                          resources:
                            limits:
                              memory: 2G
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: default
          environment:
            environmentRef: serverless
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>
