pipeline:
  name: branch-rename-again
  identifier: branch
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags: {}
  stages:
    - stage:
        name: branch
        identifier: branch
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+“deploy-ec2-“.concat(<+<+<+env.name> == “dev”>?“hom”:“”.concat(<+env.name>)>)>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: "true"
