pipeline:
  name: branch-rename-again
  identifier: branch
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags:
    app: test
    pipeline: branch
  stages:
    - stage:
        name: chain0
        identifier: chain0
        description: ""
        type: Pipeline
        spec:
          org: kartikeyaorganization
          pipeline: k8srepro
          project: CSETest1
          inputs:
            identifier: k8srepro
            stages:
              - stage:
                  identifier: k8s
                  type: Deployment
                  spec:
                    service:
                      serviceInputs:
                        serviceDefinition:
                          type: Kubernetes
                          spec:
                            artifacts:
                              primary:
                                primaryArtifactRef: k8s
                                sources:
                                  - identifier: k8s
                                    type: DockerRegistry
                                    spec:
                                      tag: stable-perl
    - stage:
        name: branch
        identifier: branch
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+“deploy-ec2-“.concat(<+<+<+env.name> == “dev”>?“hom”:“”.concat(<+env.name>)>)>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: "true"
