pipeline:
  name: branch-rename-again
  identifier: branch
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags:
    app: test
    pipeline: branch
  stages:
    - stage:
        name: branch
        identifier: branch
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: echo "<+infra.connector.name>-test"
                    environmentVariables: []
                    outputVariables: []
                    executionTarget: {}
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo test
                          echo <+stage.delegateSelectors>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - stepGroup:
                  name: test
                  identifier: test
                  steps:
                    - parallel:
                        - step:
                            type: ShellScript
                            name: ShellScript_3
                            identifier: ShellScript_3
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo hi
                                    echo <+matrix.listOfString>
                                    echo <+stage.delegateSelectors>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                        - step:
                            type: ShellScript
                            name: ShellScript_4
                            identifier: ShellScript_4
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo hi2
                                    echo <+stage.delegateSelectors>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                    - step:
                        type: ShellScript
                        name: ShellScript_5
                        identifier: ShellScript_5
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo hi3
                                echo <+stage.delegateSelectors>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
          environment:
            environmentRef: delegate
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s
        tags: {}
        delegateSelectors:
          - <+infra.connector.name>-test
        strategy:
          matrix:
            listOfString:
              - a
              - b
              - c
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: "true"
