pipeline:
  name: Multi-Env
  identifier: MultiEnv
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: parent
                  identifier: parent
                  steps:
                    - step:
                        type: ShellScript
                        name: ShellScript_1
                        identifier: ShellScript_1
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo hi
                                parentvar="123"
                          environmentVariables: []
                          outputVariables:
                            - name: parentvar
                              type: String
                              value: parentvar
                        timeout: 10m
                    - step:
                        type: ShellScript
                        name: ShellScript_3
                        identifier: ShellScript_3
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-



                                echo <+stepGroup.steps.ShellScript_1.output.outputVariables.parentvar>

                                echo break

                                echo <+execution.steps.<+stepGroup.identifier>.steps.ShellScript_1.output.outputVariables.parentvar>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
                    - stepGroup:
                        name: child
                        identifier: child
                        steps:
                          - step:
                              type: ShellScript
                              name: ShellScript_2
                              identifier: ShellScript_2
                              spec:
                                shell: Bash
                                executionTarget: {}
                                source:
                                  type: Inline
                                  spec:
                                    script: |-
                                      echo <+execution.steps.parent.steps.child.variables.childvar>
                                      echo break
                                      echo <+stepGroup.steps.child.variables.childvar>
                                      echo break
                                      echo <+execution.steps.<+stepGroup.identifier>.steps.ShellScript_1.output.outputVariables.parentvar>


                                      echo test
                                      echo <+stepGroup.getParentStepGroup>

                                      echo test2
                                      echo <+stepGroup.variables>
                                environmentVariables: []
                                outputVariables: []
                              timeout: 10m
                        variables:
                          - name: childvar
                            type: String
                            value: <+stepGroup.steps.ShellScript_1.output.outputVariables.parentvar>
                            description: ""
                            required: false
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
    - stage:
        name: Multi-env
        identifier: Multienv
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: sshservice
            serviceInputs:
              serviceDefinition:
                type: Ssh
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: Multiinfra
                gitBranch: main
                deployToAll: true
                infrastructureDefinitions: <+input>
          execution:
            steps:
              - stepGroup:
                  name: parent
                  identifier: parent
                  steps:
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: account.harnessImage
                          image: nginx
                          shell: Sh
                          command: echo hi
                          outputVariables:
                            - name: parentvar
                              type: String
                              value: test
                    - stepGroup:
                        name: child
                        identifier: child
                        steps:
                          - step:
                              type: ShellScript
                              name: ShellScript_1
                              identifier: ShellScript_1
                              spec:
                                shell: Bash
                                executionTarget: {}
                                source:
                                  type: Inline
                                  spec:
                                    script: <+execution.steps.parent.steps.child.variables.childvar>
                                environmentVariables: []
                                outputVariables: []
                              timeout: 10m
                        variables: []
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.k8s
                  variables:
                    - name: test
                      type: String
                      value: "123"
                      description: ""
                      required: false
              - step:
                  name: Deploy
                  identifier: Deploy
                  template:
                    templateRef: account.multiinra
                    versionLabel: v1
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
                          - name: WorkingDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>/tomcat/bin
            rollbackSteps:
              - step:
                  name: Rollback
                  identifier: Rollback
                  timeout: 10m
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                  template:
                    templateRef: account.Default_Install_Jar_Bash
                    templateInputs:
                      type: Command
                      spec:
                        environmentVariables:
                          - name: DestinationDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>
                          - name: WorkingDirectory
                            type: String
                            value: $HOME/<+service.name>/<+env.name>/tomcat/bin
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
