pipeline:
  name: Multi-Env
  identifier: MultiEnv
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo hi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - stepGroup:
                  name: test
                  identifier: test
                  steps:
                    - step:
                        type: Background
                        name: Background_1
                        identifier: Background_1
                        spec:
                          connectorRef: account.harnessImage
                          image: docker:dind
                          shell: Sh
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: account.harnessImage
                          image: nginx
                          shell: Sh
                          command: |-
                            echo hi
                            docker ps -a
                            sleep 100
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.k8s
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
  allowStageExecutions: true
