pipeline:
  name: Multi-Env
  identifier: MultiEnv
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: parent
                  identifier: parent
                  steps:
                    - step:
                        type: ShellScript
                        name: ShellScript_1
                        identifier: ShellScript_1
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo hi
                                parentvar="123"
                          environmentVariables: []
                          outputVariables:
                            - name: parentvar
                              type: String
                              value: parentvar
                        timeout: 10m
                    - step:
                        type: ShellScript
                        name: ShellScript_3
                        identifier: ShellScript_3
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-



                                echo <+stepGroup.steps.ShellScript_1.output.outputVariables.parentvar>

                                echo break

                                echo <+execution.steps.<+stepGroup.identifier>.steps.ShellScript_1.output.outputVariables.parentvar>
                          environmentVariables: []
                          outputVariables: []
                        timeout: 10m
                    - stepGroup:
                        name: child
                        identifier: child
                        steps:
                          - step:
                              type: ShellScript
                              name: ShellScript_2
                              identifier: ShellScript_2
                              spec:
                                shell: Bash
                                executionTarget: {}
                                source:
                                  type: Inline
                                  spec:
                                    script: |-
                                      echo <+execution.steps.parent.steps.child.variables.childvar>
                                      echo break
                                      echo <+stepGroup.steps.child.variables.childvar>
                                      echo break
                                      echo <+execution.steps.<+stepGroup.identifier>.steps.ShellScript_1.output.outputVariables.parentvar>


                                      echo test
                                      echo <+stepGroup.getParentStepGroup>

                                      echo test2
                                      echo <+stepGroup.variables>
                                environmentVariables: []
                                outputVariables: []
                              timeout: 10m
                        variables:
                          - name: childvar
                            type: String
                            value: <+execution.steps.<+stepGroup.identifier>.steps.ShellScript_1.output.outputVariables.parentvar>
                            description: ""
                            required: false
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
  allowStageExecutions: true
