pipeline:
  name: conditional
  identifier: conditional
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags: {}
  stages:
    - stage:
        name: condition
        identifier: condition
        when:
          pipelineStatus: Success
          condition: <+pipeline.variables.DeployUAE>="true"
        tags: {}
        template:
          templateRef: account.save
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
