pipeline:
  name: Multi SerEnv
  identifier: Multi_SerEnv
  projectIdentifier: CSETest1
  orgIdentifier: kartikeyaorganization
  tags:
    ai_generated: "true"
  variables:
    - name: tagFilter
      type: String
      value: allowed
  stages:
    - stage:
        name: Multi
        identifier: Multi
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          services:
            values:
              - serviceRef: scope
            metadata:
              parallel: false
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: Multiinfra
                deployToAll: true
                infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "filter testing"
                          echo <+service.tags>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  description: This pipeline was updated by Harness AI on 2025-12-15 11:14:51 UTC by Shylaja Sundararajan.
